# Generated by Django 4.1 on 2022-11-23 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_mywatchlist_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlist',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mywatchlist',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mywatchlist',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
